//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.0.30319.17929.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.starstandard.org/STAR/5")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.starstandard.org/STAR/5", IsNullable=false)]
public partial class LaborOperationCodes {
    
    private LaborOperationCodesMajorGroup[] itemsField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("MajorGroup")]
    public LaborOperationCodesMajorGroup[] Items {
        get {
            return this.itemsField;
        }
        set {
            this.itemsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.starstandard.org/STAR/5")]
public partial class LaborOperationCodesMajorGroup {
    
    private string majorGroupIDField;
    
    private string majorGroupDescriptionField;
    
    /// <remarks/>
    public string MajorGroupID {
        get {
            return this.majorGroupIDField;
        }
        set {
            this.majorGroupIDField = value;
        }
    }
    
    /// <remarks/>
    public string MajorGroupDescription {
        get {
            return this.majorGroupDescriptionField;
        }
        set {
            this.majorGroupDescriptionField = value;
        }
    }
}
