//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenMateNET.Lib.ProcessSubscriptionService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://inbound.verbs.openmate.automate.com/", ConfigurationName="ProcessSubscriptionService.ProcessSubscription")]
    internal interface ProcessSubscription {
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="urn:Subscribe", ReplyAction="http://inbound.verbs.openmate.automate.com/ProcessSubscription/subscribeResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        OpenMateNET.Lib.ProcessSubscriptionService.subscribeResponse subscribe(OpenMateNET.Lib.ProcessSubscriptionService.subscribeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:Subscribe", ReplyAction="http://inbound.verbs.openmate.automate.com/ProcessSubscription/subscribeResponse")]
        System.Threading.Tasks.Task<OpenMateNET.Lib.ProcessSubscriptionService.subscribeResponse> subscribeAsync(OpenMateNET.Lib.ProcessSubscriptionService.subscribeRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="urn:getSubscriptions", ReplyAction="http://inbound.verbs.openmate.automate.com/ProcessSubscription/getSubscriptionsRe" +
            "sponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        OpenMateNET.Lib.ProcessSubscriptionService.getSubscriptionsResponse getSubscriptions(OpenMateNET.Lib.ProcessSubscriptionService.getSubscriptionsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:getSubscriptions", ReplyAction="http://inbound.verbs.openmate.automate.com/ProcessSubscription/getSubscriptionsRe" +
            "sponse")]
        System.Threading.Tasks.Task<OpenMateNET.Lib.ProcessSubscriptionService.getSubscriptionsResponse> getSubscriptionsAsync(OpenMateNET.Lib.ProcessSubscriptionService.getSubscriptionsRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="urn:getEndpointSubscriptions", ReplyAction="http://inbound.verbs.openmate.automate.com/ProcessSubscription/getEndpointSubscri" +
            "ptionsResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        OpenMateNET.Lib.ProcessSubscriptionService.getEndpointSubscriptionsResponse getEndpointSubscriptions(OpenMateNET.Lib.ProcessSubscriptionService.getEndpointSubscriptionsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:getEndpointSubscriptions", ReplyAction="http://inbound.verbs.openmate.automate.com/ProcessSubscription/getEndpointSubscri" +
            "ptionsResponse")]
        System.Threading.Tasks.Task<OpenMateNET.Lib.ProcessSubscriptionService.getEndpointSubscriptionsResponse> getEndpointSubscriptionsAsync(OpenMateNET.Lib.ProcessSubscriptionService.getEndpointSubscriptionsRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="urn:UnSubscribe", ReplyAction="http://inbound.verbs.openmate.automate.com/ProcessSubscription/unSubscribeRespons" +
            "e")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        OpenMateNET.Lib.ProcessSubscriptionService.unSubscribeResponse unSubscribe(OpenMateNET.Lib.ProcessSubscriptionService.unSubscribeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:UnSubscribe", ReplyAction="http://inbound.verbs.openmate.automate.com/ProcessSubscription/unSubscribeRespons" +
            "e")]
        System.Threading.Tasks.Task<OpenMateNET.Lib.ProcessSubscriptionService.unSubscribeResponse> unSubscribeAsync(OpenMateNET.Lib.ProcessSubscriptionService.unSubscribeRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18034")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://inbound.verbs.openmate.automate.com/")]
    public partial class authenticationToken : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string userNameField;
        
        private string passwordField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string userName {
            get {
                return this.userNameField;
            }
            set {
                this.userNameField = value;
                this.RaisePropertyChanged("userName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
                this.RaisePropertyChanged("password");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18034")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://inbound.verbs.openmate.automate.com/")]
    public partial class subscription : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int dealerEndpointIdField;
        
        private int thirdPartyIdField;
        
        private transactionType typeField;
        
        private bool typeFieldSpecified;
        
        private bool isSubscribedField;
        
        private string callbackField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int dealerEndpointId {
            get {
                return this.dealerEndpointIdField;
            }
            set {
                this.dealerEndpointIdField = value;
                this.RaisePropertyChanged("dealerEndpointId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int thirdPartyId {
            get {
                return this.thirdPartyIdField;
            }
            set {
                this.thirdPartyIdField = value;
                this.RaisePropertyChanged("thirdPartyId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public transactionType type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
                this.RaisePropertyChanged("type");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool typeSpecified {
            get {
                return this.typeFieldSpecified;
            }
            set {
                this.typeFieldSpecified = value;
                this.RaisePropertyChanged("typeSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public bool isSubscribed {
            get {
                return this.isSubscribedField;
            }
            set {
                this.isSubscribedField = value;
                this.RaisePropertyChanged("isSubscribed");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string callback {
            get {
                return this.callbackField;
            }
            set {
                this.callbackField = value;
                this.RaisePropertyChanged("callback");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18034")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://inbound.verbs.openmate.automate.com/")]
    public enum transactionType {
        
        /// <remarks/>
        DealerUp,
        
        /// <remarks/>
        DealerDown,
        
        /// <remarks/>
        ProcessVehicleInventoryBatch,
        
        /// <remarks/>
        ProcessVehicleInventoryChange,
        
        /// <remarks/>
        ProcessVehicleInventoryAdd,
        
        /// <remarks/>
        ProcessVehicleDeleted,
        
        /// <remarks/>
        ProcessCustomerChange,
        
        /// <remarks/>
        ProcessCustomerAdd,
        
        /// <remarks/>
        ProcessCustomerDeleted,
        
        /// <remarks/>
        ProcessDealChange,
        
        /// <remarks/>
        ProcessDealAdd,
        
        /// <remarks/>
        ProcessDealDeleted,
        
        /// <remarks/>
        GetSalespersonConfig,
        
        /// <remarks/>
        GetDealFees,
        
        /// <remarks/>
        GetDealAccessories,
        
        /// <remarks/>
        GetDealRebates,
        
        /// <remarks/>
        GetDealIncentives,
        
        /// <remarks/>
        GetDealInsuranceCompanies,
        
        /// <remarks/>
        GetDealServiceWarranties,
        
        /// <remarks/>
        GetDealLenders,
        
        /// <remarks/>
        ProcessServiceAppointmentCancel,
        
        /// <remarks/>
        ProcessServiceAppointmentAdd,
        
        /// <remarks/>
        ProcessServiceAppointmentChange,
        
        /// <remarks/>
        RepairOrderStatusChanged,
        
        /// <remarks/>
        GetAdvisorConfig,
        
        /// <remarks/>
        GetServiceCatalog,
        
        /// <remarks/>
        GetRepairOrderStatuses,
        
        /// <remarks/>
        ProcessCreditAppAdd,
        
        /// <remarks/>
        ProcessCreditAppChange,
        
        /// <remarks/>
        GetVehicleInventoryKeys,
        
        /// <remarks/>
        GetServiceAppointmentKeys,
        
        /// <remarks/>
        GetDealKeys,
        
        /// <remarks/>
        GetRepairOrderKeys,
        
        /// <remarks/>
        GetCustomerKeys,
        
        /// <remarks/>
        GetCustomers,
        
        /// <remarks/>
        GetVehicleInventory,
        
        /// <remarks/>
        GetRepairOrders,
        
        /// <remarks/>
        GetServiceAppointments,
        
        /// <remarks/>
        ProcessFinancialStatement,
        
        /// <remarks/>
        GetDeals,
        
        /// <remarks/>
        ProcessCommand,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18034")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://inbound.verbs.openmate.automate.com/")]
    public partial class subscriptionCallback : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string uriField;
        
        private string apiVersionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string uri {
            get {
                return this.uriField;
            }
            set {
                this.uriField = value;
                this.RaisePropertyChanged("uri");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string apiVersion {
            get {
                return this.apiVersionField;
            }
            set {
                this.apiVersionField = value;
                this.RaisePropertyChanged("apiVersion");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18034")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://inbound.verbs.openmate.automate.com/")]
    public enum subscriptionResult {
        
        /// <remarks/>
        Sucess,
        
        /// <remarks/>
        Denied,
        
        /// <remarks/>
        ValidationFailure,
        
        /// <remarks/>
        InternalFailure,
        
        /// <remarks/>
        Duplicate,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="subscribe", WrapperNamespace="http://inbound.verbs.openmate.automate.com/", IsWrapped=true)]
    internal partial class subscribeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://inbound.verbs.openmate.automate.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public OpenMateNET.Lib.ProcessSubscriptionService.authenticationToken authenticationToken;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://inbound.verbs.openmate.automate.com/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int dealerEndpointId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://inbound.verbs.openmate.automate.com/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int thirdPartyId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://inbound.verbs.openmate.automate.com/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public OpenMateNET.Lib.ProcessSubscriptionService.transactionType transactionType;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://inbound.verbs.openmate.automate.com/", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public OpenMateNET.Lib.ProcessSubscriptionService.subscriptionCallback callback;
        
        public subscribeRequest() {
        }
        
        public subscribeRequest(OpenMateNET.Lib.ProcessSubscriptionService.authenticationToken authenticationToken, int dealerEndpointId, int thirdPartyId, OpenMateNET.Lib.ProcessSubscriptionService.transactionType transactionType, OpenMateNET.Lib.ProcessSubscriptionService.subscriptionCallback callback) {
            this.authenticationToken = authenticationToken;
            this.dealerEndpointId = dealerEndpointId;
            this.thirdPartyId = thirdPartyId;
            this.transactionType = transactionType;
            this.callback = callback;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="subscribeResponse", WrapperNamespace="http://inbound.verbs.openmate.automate.com/", IsWrapped=true)]
    internal partial class subscribeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://inbound.verbs.openmate.automate.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public OpenMateNET.Lib.ProcessSubscriptionService.subscriptionResult @return;
        
        public subscribeResponse() {
        }
        
        public subscribeResponse(OpenMateNET.Lib.ProcessSubscriptionService.subscriptionResult @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getSubscriptions", WrapperNamespace="http://inbound.verbs.openmate.automate.com/", IsWrapped=true)]
    internal partial class getSubscriptionsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://inbound.verbs.openmate.automate.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public OpenMateNET.Lib.ProcessSubscriptionService.authenticationToken authenticationToken;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://inbound.verbs.openmate.automate.com/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int thirdPartyId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://inbound.verbs.openmate.automate.com/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public OpenMateNET.Lib.ProcessSubscriptionService.transactionType transactionType;
        
        public getSubscriptionsRequest() {
        }
        
        public getSubscriptionsRequest(OpenMateNET.Lib.ProcessSubscriptionService.authenticationToken authenticationToken, int thirdPartyId, OpenMateNET.Lib.ProcessSubscriptionService.transactionType transactionType) {
            this.authenticationToken = authenticationToken;
            this.thirdPartyId = thirdPartyId;
            this.transactionType = transactionType;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getSubscriptionsResponse", WrapperNamespace="http://inbound.verbs.openmate.automate.com/", IsWrapped=true)]
    internal partial class getSubscriptionsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://inbound.verbs.openmate.automate.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public OpenMateNET.Lib.ProcessSubscriptionService.subscription[] @return;
        
        public getSubscriptionsResponse() {
        }
        
        public getSubscriptionsResponse(OpenMateNET.Lib.ProcessSubscriptionService.subscription[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getEndpointSubscriptions", WrapperNamespace="http://inbound.verbs.openmate.automate.com/", IsWrapped=true)]
    internal partial class getEndpointSubscriptionsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://inbound.verbs.openmate.automate.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public OpenMateNET.Lib.ProcessSubscriptionService.authenticationToken authenticationToken;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://inbound.verbs.openmate.automate.com/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int thirdPartyId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://inbound.verbs.openmate.automate.com/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int endpointId;
        
        public getEndpointSubscriptionsRequest() {
        }
        
        public getEndpointSubscriptionsRequest(OpenMateNET.Lib.ProcessSubscriptionService.authenticationToken authenticationToken, int thirdPartyId, int endpointId) {
            this.authenticationToken = authenticationToken;
            this.thirdPartyId = thirdPartyId;
            this.endpointId = endpointId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getEndpointSubscriptionsResponse", WrapperNamespace="http://inbound.verbs.openmate.automate.com/", IsWrapped=true)]
    internal partial class getEndpointSubscriptionsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://inbound.verbs.openmate.automate.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public OpenMateNET.Lib.ProcessSubscriptionService.subscription[] @return;
        
        public getEndpointSubscriptionsResponse() {
        }
        
        public getEndpointSubscriptionsResponse(OpenMateNET.Lib.ProcessSubscriptionService.subscription[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="unSubscribe", WrapperNamespace="http://inbound.verbs.openmate.automate.com/", IsWrapped=true)]
    internal partial class unSubscribeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://inbound.verbs.openmate.automate.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public OpenMateNET.Lib.ProcessSubscriptionService.authenticationToken authenticationToken;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://inbound.verbs.openmate.automate.com/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int dealerEndpointId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://inbound.verbs.openmate.automate.com/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int thirdPartyId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://inbound.verbs.openmate.automate.com/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public OpenMateNET.Lib.ProcessSubscriptionService.transactionType transactionType;
        
        public unSubscribeRequest() {
        }
        
        public unSubscribeRequest(OpenMateNET.Lib.ProcessSubscriptionService.authenticationToken authenticationToken, int dealerEndpointId, int thirdPartyId, OpenMateNET.Lib.ProcessSubscriptionService.transactionType transactionType) {
            this.authenticationToken = authenticationToken;
            this.dealerEndpointId = dealerEndpointId;
            this.thirdPartyId = thirdPartyId;
            this.transactionType = transactionType;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="unSubscribeResponse", WrapperNamespace="http://inbound.verbs.openmate.automate.com/", IsWrapped=true)]
    internal partial class unSubscribeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://inbound.verbs.openmate.automate.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public OpenMateNET.Lib.ProcessSubscriptionService.subscriptionResult @return;
        
        public unSubscribeResponse() {
        }
        
        public unSubscribeResponse(OpenMateNET.Lib.ProcessSubscriptionService.subscriptionResult @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    internal interface ProcessSubscriptionChannel : OpenMateNET.Lib.ProcessSubscriptionService.ProcessSubscription, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    internal partial class ProcessSubscriptionClient : System.ServiceModel.ClientBase<OpenMateNET.Lib.ProcessSubscriptionService.ProcessSubscription>, OpenMateNET.Lib.ProcessSubscriptionService.ProcessSubscription {
        
        public ProcessSubscriptionClient() {
        }
        
        public ProcessSubscriptionClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ProcessSubscriptionClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProcessSubscriptionClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProcessSubscriptionClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        OpenMateNET.Lib.ProcessSubscriptionService.subscribeResponse OpenMateNET.Lib.ProcessSubscriptionService.ProcessSubscription.subscribe(OpenMateNET.Lib.ProcessSubscriptionService.subscribeRequest request) {
            return base.Channel.subscribe(request);
        }
        
        public OpenMateNET.Lib.ProcessSubscriptionService.subscriptionResult subscribe(OpenMateNET.Lib.ProcessSubscriptionService.authenticationToken authenticationToken, int dealerEndpointId, int thirdPartyId, OpenMateNET.Lib.ProcessSubscriptionService.transactionType transactionType, OpenMateNET.Lib.ProcessSubscriptionService.subscriptionCallback callback) {
            OpenMateNET.Lib.ProcessSubscriptionService.subscribeRequest inValue = new OpenMateNET.Lib.ProcessSubscriptionService.subscribeRequest();
            inValue.authenticationToken = authenticationToken;
            inValue.dealerEndpointId = dealerEndpointId;
            inValue.thirdPartyId = thirdPartyId;
            inValue.transactionType = transactionType;
            inValue.callback = callback;
            OpenMateNET.Lib.ProcessSubscriptionService.subscribeResponse retVal = ((OpenMateNET.Lib.ProcessSubscriptionService.ProcessSubscription)(this)).subscribe(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<OpenMateNET.Lib.ProcessSubscriptionService.subscribeResponse> OpenMateNET.Lib.ProcessSubscriptionService.ProcessSubscription.subscribeAsync(OpenMateNET.Lib.ProcessSubscriptionService.subscribeRequest request) {
            return base.Channel.subscribeAsync(request);
        }
        
        public System.Threading.Tasks.Task<OpenMateNET.Lib.ProcessSubscriptionService.subscribeResponse> subscribeAsync(OpenMateNET.Lib.ProcessSubscriptionService.authenticationToken authenticationToken, int dealerEndpointId, int thirdPartyId, OpenMateNET.Lib.ProcessSubscriptionService.transactionType transactionType, OpenMateNET.Lib.ProcessSubscriptionService.subscriptionCallback callback) {
            OpenMateNET.Lib.ProcessSubscriptionService.subscribeRequest inValue = new OpenMateNET.Lib.ProcessSubscriptionService.subscribeRequest();
            inValue.authenticationToken = authenticationToken;
            inValue.dealerEndpointId = dealerEndpointId;
            inValue.thirdPartyId = thirdPartyId;
            inValue.transactionType = transactionType;
            inValue.callback = callback;
            return ((OpenMateNET.Lib.ProcessSubscriptionService.ProcessSubscription)(this)).subscribeAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        OpenMateNET.Lib.ProcessSubscriptionService.getSubscriptionsResponse OpenMateNET.Lib.ProcessSubscriptionService.ProcessSubscription.getSubscriptions(OpenMateNET.Lib.ProcessSubscriptionService.getSubscriptionsRequest request) {
            return base.Channel.getSubscriptions(request);
        }
        
        public OpenMateNET.Lib.ProcessSubscriptionService.subscription[] getSubscriptions(OpenMateNET.Lib.ProcessSubscriptionService.authenticationToken authenticationToken, int thirdPartyId, OpenMateNET.Lib.ProcessSubscriptionService.transactionType transactionType) {
            OpenMateNET.Lib.ProcessSubscriptionService.getSubscriptionsRequest inValue = new OpenMateNET.Lib.ProcessSubscriptionService.getSubscriptionsRequest();
            inValue.authenticationToken = authenticationToken;
            inValue.thirdPartyId = thirdPartyId;
            inValue.transactionType = transactionType;
            OpenMateNET.Lib.ProcessSubscriptionService.getSubscriptionsResponse retVal = ((OpenMateNET.Lib.ProcessSubscriptionService.ProcessSubscription)(this)).getSubscriptions(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<OpenMateNET.Lib.ProcessSubscriptionService.getSubscriptionsResponse> OpenMateNET.Lib.ProcessSubscriptionService.ProcessSubscription.getSubscriptionsAsync(OpenMateNET.Lib.ProcessSubscriptionService.getSubscriptionsRequest request) {
            return base.Channel.getSubscriptionsAsync(request);
        }
        
        public System.Threading.Tasks.Task<OpenMateNET.Lib.ProcessSubscriptionService.getSubscriptionsResponse> getSubscriptionsAsync(OpenMateNET.Lib.ProcessSubscriptionService.authenticationToken authenticationToken, int thirdPartyId, OpenMateNET.Lib.ProcessSubscriptionService.transactionType transactionType) {
            OpenMateNET.Lib.ProcessSubscriptionService.getSubscriptionsRequest inValue = new OpenMateNET.Lib.ProcessSubscriptionService.getSubscriptionsRequest();
            inValue.authenticationToken = authenticationToken;
            inValue.thirdPartyId = thirdPartyId;
            inValue.transactionType = transactionType;
            return ((OpenMateNET.Lib.ProcessSubscriptionService.ProcessSubscription)(this)).getSubscriptionsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        OpenMateNET.Lib.ProcessSubscriptionService.getEndpointSubscriptionsResponse OpenMateNET.Lib.ProcessSubscriptionService.ProcessSubscription.getEndpointSubscriptions(OpenMateNET.Lib.ProcessSubscriptionService.getEndpointSubscriptionsRequest request) {
            return base.Channel.getEndpointSubscriptions(request);
        }
        
        public OpenMateNET.Lib.ProcessSubscriptionService.subscription[] getEndpointSubscriptions(OpenMateNET.Lib.ProcessSubscriptionService.authenticationToken authenticationToken, int thirdPartyId, int endpointId) {
            OpenMateNET.Lib.ProcessSubscriptionService.getEndpointSubscriptionsRequest inValue = new OpenMateNET.Lib.ProcessSubscriptionService.getEndpointSubscriptionsRequest();
            inValue.authenticationToken = authenticationToken;
            inValue.thirdPartyId = thirdPartyId;
            inValue.endpointId = endpointId;
            OpenMateNET.Lib.ProcessSubscriptionService.getEndpointSubscriptionsResponse retVal = ((OpenMateNET.Lib.ProcessSubscriptionService.ProcessSubscription)(this)).getEndpointSubscriptions(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<OpenMateNET.Lib.ProcessSubscriptionService.getEndpointSubscriptionsResponse> OpenMateNET.Lib.ProcessSubscriptionService.ProcessSubscription.getEndpointSubscriptionsAsync(OpenMateNET.Lib.ProcessSubscriptionService.getEndpointSubscriptionsRequest request) {
            return base.Channel.getEndpointSubscriptionsAsync(request);
        }
        
        public System.Threading.Tasks.Task<OpenMateNET.Lib.ProcessSubscriptionService.getEndpointSubscriptionsResponse> getEndpointSubscriptionsAsync(OpenMateNET.Lib.ProcessSubscriptionService.authenticationToken authenticationToken, int thirdPartyId, int endpointId) {
            OpenMateNET.Lib.ProcessSubscriptionService.getEndpointSubscriptionsRequest inValue = new OpenMateNET.Lib.ProcessSubscriptionService.getEndpointSubscriptionsRequest();
            inValue.authenticationToken = authenticationToken;
            inValue.thirdPartyId = thirdPartyId;
            inValue.endpointId = endpointId;
            return ((OpenMateNET.Lib.ProcessSubscriptionService.ProcessSubscription)(this)).getEndpointSubscriptionsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        OpenMateNET.Lib.ProcessSubscriptionService.unSubscribeResponse OpenMateNET.Lib.ProcessSubscriptionService.ProcessSubscription.unSubscribe(OpenMateNET.Lib.ProcessSubscriptionService.unSubscribeRequest request) {
            return base.Channel.unSubscribe(request);
        }
        
        public OpenMateNET.Lib.ProcessSubscriptionService.subscriptionResult unSubscribe(OpenMateNET.Lib.ProcessSubscriptionService.authenticationToken authenticationToken, int dealerEndpointId, int thirdPartyId, OpenMateNET.Lib.ProcessSubscriptionService.transactionType transactionType) {
            OpenMateNET.Lib.ProcessSubscriptionService.unSubscribeRequest inValue = new OpenMateNET.Lib.ProcessSubscriptionService.unSubscribeRequest();
            inValue.authenticationToken = authenticationToken;
            inValue.dealerEndpointId = dealerEndpointId;
            inValue.thirdPartyId = thirdPartyId;
            inValue.transactionType = transactionType;
            OpenMateNET.Lib.ProcessSubscriptionService.unSubscribeResponse retVal = ((OpenMateNET.Lib.ProcessSubscriptionService.ProcessSubscription)(this)).unSubscribe(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<OpenMateNET.Lib.ProcessSubscriptionService.unSubscribeResponse> OpenMateNET.Lib.ProcessSubscriptionService.ProcessSubscription.unSubscribeAsync(OpenMateNET.Lib.ProcessSubscriptionService.unSubscribeRequest request) {
            return base.Channel.unSubscribeAsync(request);
        }
        
        public System.Threading.Tasks.Task<OpenMateNET.Lib.ProcessSubscriptionService.unSubscribeResponse> unSubscribeAsync(OpenMateNET.Lib.ProcessSubscriptionService.authenticationToken authenticationToken, int dealerEndpointId, int thirdPartyId, OpenMateNET.Lib.ProcessSubscriptionService.transactionType transactionType) {
            OpenMateNET.Lib.ProcessSubscriptionService.unSubscribeRequest inValue = new OpenMateNET.Lib.ProcessSubscriptionService.unSubscribeRequest();
            inValue.authenticationToken = authenticationToken;
            inValue.dealerEndpointId = dealerEndpointId;
            inValue.thirdPartyId = thirdPartyId;
            inValue.transactionType = transactionType;
            return ((OpenMateNET.Lib.ProcessSubscriptionService.ProcessSubscription)(this)).unSubscribeAsync(inValue);
        }
    }
}
